apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slick-ws-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /slick
        pathType: Prefix
        backend:
          service:
            name: slick
            port:
              number: 8080
